Repository archspec/archspec-json, pull requests merged in 2023-04, with the labels that each got.

#65 Apple M2: fix microarchitecture optimization flags
  cpu/microarchitectures.json
Labels: bug

#64 neoverse-v1: fix flags for GCC
  cpu/microarchitectures.json
Labels: bug, enhancement

#67 add nvhpc support
  cpu/microarchitectures.json
Labels: enhancement
